### ISSUE TITLE
bug:  Error: Unsupported block type

### ISSUE THREAD

**Issue by xomgc3** [lacework/terraform-aws-agentless-scanning#83]
**Describe the bug**
The module is using an unsupported argument for the `lacework_integration_aws_org_agentless_scanning` resource.

**Steps to reproduce**
According to the [docs](https://registry.terraform.io/providers/lacework/lacework/latest/docs/resources/integration_aws_org_agentless_scanning), `org_account_mappings` is not a valid argument.  However, this module [hasn’t been updated](https://github.com/lacework/terraform-aws-agentless-scanning/blob/main/main.tf#L123).

**Expected behavior**
No errors for accepted inputs when using this module.

**Screenshots**
```
Error: Unsupported block type
│ 
│   on .terraform/modules/lacework_agentless_scanning_org/main.tf line 123, in resource "lacework_integration_aws_org_agentless_scanning" "lacework_cloud_account":
│  123:   dynamic "org_account_mappings" {
│ 
│ Blocks of type "org_account_mappings" are not expected here.
```

**Please complete the following information):**
 - Terraform Version: `1.2.1`
 - Module Version: `~> 0.6`

**Additional context**
Does LW actively manage these TF modules?

**Comment by afiune** [comment]
@xomgc3 Hi there 👋🏽 - Lacework does actively manage these Terraform modules so we
appreciate that you are reaching out to us and we apologies for the inconveniences of this
bug.

My gut tells me that we might have forgotten to bump the required version of the Terraform
provider for Lacework where we introduced this new field `org_account_mappings`, which
was introduced on version `1.8.0`.

Your problem should be fixed by running `terraform init -upgrade`.

In the meantime, we are going to bump the version [here](https://github.com/lacework/terraform-aws-agentless-scanning/blob/main/versions.tf#L9) and release a new version of this
module with that fix.
